### ISSUE TITLE
Add Drupal 8 Twig Filters

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic-twig-filters#10]
clean_id
clean_class
etc.

**Comment by soniktrooth** [comment]
Heres a comprehensive list: http://www.opin.ca/en/article/twig-filters-drupal-8

**Comment by RobLoach** [comment]
Wait, I already did this:
https://github.com/kalamuna/twig-drupal-filters

**Comment by soniktrooth** [comment]
LOL
